name: Build Jellyfin Plugin

on:
  push:
    tags:
      - 'v*'
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release -o output

      - name: Zip plugin
        run: |
          cd output
          zip -r ../Jellyfin.MAL.Plugin.zip ./JellyFin.Plugin.Mal.dll ./JikanDotNet.dll ./System.Linq.Async.dll

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Jellyfin.MAL.Plugin.zip
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
